# Указываем resolver для динамического разрешения имён
resolver 127.0.0.11 valid=10s;

server {
    listen 80;
    # Явно принимаем запросы с этого домена (Traefik передаёт Host от клиента)
    server_name site.local localhost _;
    root /var/www/html/web;

    index index.php index.html;

    set_real_ip_from 172.31.0.0/16; 
    real_ip_header X-Forwarded-For;
    real_ip_recursive on;

    location / {
        try_files $uri $uri/ /index.php?$args;  # Перенаправляем все запросы на index.php, если файл не найден
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}